# Generated by Django 5.0.6 on 2024-08-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_period', models.DateField(verbose_name='Начало периода')),
                ('end_period', models.DateField(verbose_name='Конец периода')),
                ('site', models.CharField(max_length=100, verbose_name='Сайт')),
                ('segment', models.CharField(max_length=100, verbose_name='Сегмент')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Бюджет')),
                ('clicks', models.PositiveIntegerField(verbose_name='Клики')),
                ('leads', models.PositiveIntegerField(verbose_name='Кол-во Лидов')),
                ('unqualified_leads', models.PositiveIntegerField(verbose_name='Кол-во некач. Лидов')),
                ('deals', models.PositiveIntegerField(verbose_name='Кол-во Сделок')),
                ('qualified_deals', models.PositiveIntegerField(verbose_name='Кол-во Сделок качественных')),
                ('failed_deals', models.PositiveIntegerField(verbose_name='Кол-во проваленных Сделок')),
                ('ignored_failed_deals', models.PositiveIntegerField(verbose_name='Кол-во проваленных Сделок по причине игнор дел')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Выручка')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
    ]
