# Generated by Django 5.0.6 on 2024-08-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='clicks',
            field=models.IntegerField(verbose_name='Клики'),
        ),
        migrations.AlterField(
            model_name='report',
            name='deals',
            field=models.IntegerField(verbose_name='Кол-во Сделок'),
        ),
        migrations.AlterField(
            model_name='report',
            name='failed_deals',
            field=models.IntegerField(verbose_name='Кол-во проваленных Сделок'),
        ),
        migrations.AlterField(
            model_name='report',
            name='ignored_failed_deals',
            field=models.IntegerField(verbose_name='Кол-во проваленных Сделок по причине игнор дел'),
        ),
        migrations.AlterField(
            model_name='report',
            name='leads',
            field=models.IntegerField(verbose_name='Кол-во Лидов'),
        ),
        migrations.AlterField(
            model_name='report',
            name='qualified_deals',
            field=models.IntegerField(verbose_name='Кол-во Сделок качественных'),
        ),
        migrations.AlterField(
            model_name='report',
            name='unqualified_leads',
            field=models.IntegerField(verbose_name='Кол-во некач. Лидов'),
        ),
    ]
